apiVersion: v2
name: simple-web-default
description: Simple web service for default cluster
type: application
version: 0.1.0

dependencies:
  - name: simple-web
    repository: file://../../../../../charts/simple-web
    version: 0.1.0