spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/hoonii2/argocd-app.git
    targetRevision: main

apps:
  simpleweb:
    enabled: true
    namespace: default
    path: simple-web