{{- if .Values.apps.simpleWeb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-web
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: {{ .Values.apps.simpleWeb.path }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.apps.simpleWeb.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}