apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    team: {{ .Values.team }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        team: {{ .Values.team }}
        environment: {{ .Values.environment }}
    spec:
      tolerations:
        - key: team
          operator: Equal
          value: {{ .Values.team }}
          effect: NoSchedule
        - key: architecture
          operator: Equal
          value: {{ .Values.architecture }}
          effect: NoSchedule

      nodeSelector:
        kubernetes.io/arch: {{ .Values.architecture }}
        team: {{ .Values.team }}

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP

        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}

        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
