# 기본값만 정의 (각 환경에서 오버라이드)
replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: "0.2.3"
  pullPolicy: IfNotPresent

# Architecture: arm64 or amd64
architecture: "amd64"

clusterName: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 5678

ingress:
  enabled: true
  ingressClassName: alb
  hostname: ""
  annotations: {}

istio:
  enabled: false
  host: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi