apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hoonii2/argocd-app.git
    targetRevision: main
    path: charts/simple-web                     # 공통 차트 직접 참조
    helm:
      valueFiles:
      - ../../common-apps/green/values/simple-web.yaml  # 환경별 values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true