{{- if .Values.nodePool.spot.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot
  labels:
    {{- include "karpenter-config.labels" . | nindent 4 }}
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.ec2NodeClass.name }}
      
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            {{- range .Values.nodePool.spot.instanceTypes }}
            - {{ . | quote }}
            {{- end }}
        
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
      
      # Spot 표시용 Taint
      taints:
        - key: karpenter.sh/spot
          value: "true"
          effect: NoSchedule
  
  limits:
    cpu: {{ .Values.nodePool.spot.limits.cpu | quote }}
    memory: {{ .Values.nodePool.spot.limits.memory | quote }}
  
  weight: {{ .Values.nodePool.spot.weight }}
  
  disruption:
    consolidationPolicy: {{ .Values.nodePool.spot.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.nodePool.spot.disruption.consolidateAfter }}
    budgets:
      {{- toYaml .Values.nodePool.spot.disruption.budgets | nindent 6 }}
{{- end }}