{{- if .Values.nodePool.ondemand.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ondemand
  labels:
    {{- include "karpenter-config.labels" . | nindent 4 }}
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.ec2NodeClass.name }}
      
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            {{- range .Values.nodePool.ondemand.instanceTypes }}
            - {{ . | quote }}
            {{- end }}
        
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
  
  limits:
    cpu: {{ .Values.nodePool.ondemand.limits.cpu | quote }}
    memory: {{ .Values.nodePool.ondemand.limits.memory | quote }}
  
  weight: {{ .Values.nodePool.ondemand.weight }}
  
  disruption:
    consolidationPolicy: {{ .Values.nodePool.ondemand.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.nodePool.ondemand.disruption.consolidateAfter }}
    budgets:
      {{- toYaml .Values.nodePool.ondemand.disruption.budgets | nindent 6 }}
{{- end }}