apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # 가장 먼저 설치
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.24.2
    chart: base
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/hoonii2/argocd-app/main/common-apps/default/values/istio-base.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
