apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/hoonii2/argocd-app.git
    path: charts/backend-api
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      values: |
        environment: dev
        replicaCount: 1

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: backend-team-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
