apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobile-gateway-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: mobile-gateway=476120258327.dkr.ecr.ap-northeast-2.amazonaws.com/my-cluster/mobile-gateway:latest
    argocd-image-updater.argoproj.io/mobile-gateway.update-strategy: digest
    argocd-image-updater.argoproj.io/mobile-gateway.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/mobile-gateway.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hoonii2/argocd-app.git
    path: charts/mobile-gateway
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      values: |
        environment: dev
        replicaCount: 1

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: android-team-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
